"""Модель данных п. 0.2: справочники (dict_*), пользователи и группы, сценарии, занятия, назначения,
карточки 112 и службы, очередь ДДС, события действий, оценки, отчёты, аудит.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-26 16:21:59.353971
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision: str = "0002"
down_revision: str | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.Column("card_number", sa.BigInteger(), nullable=True),
        sa.Column("operator_number", sa.String(length=16), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("actor_name", sa.String(length=255), nullable=True),
        sa.Column("arm_number", sa.String(length=16), nullable=True),
        sa.Column("event", sa.String(length=64), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("object_type", sa.String(length=32), nullable=True),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("data", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_actor_id"), "audit_log", ["actor_id"], unique=False)
    op.create_index(op.f("ix_audit_log_at"), "audit_log", ["at"], unique=False)
    op.create_index(op.f("ix_audit_log_card_number"), "audit_log", ["card_number"], unique=False)
    op.create_index(op.f("ix_audit_log_event"), "audit_log", ["event"], unique=False)
    op.create_table(
        "dict_card_types",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=True),
        sa.Column("sign1", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column(
            "synonyms", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("quick", sa.Boolean(), nullable=False),
        sa.Column("significant", sa.Boolean(), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_dict_card_types")),
    )
    op.create_table(
        "dict_enums",
        sa.Column("domain", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("sort", sa.Integer(), nullable=False),
        sa.Column("attrs", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.PrimaryKeyConstraint("domain", "code", name=op.f("pk_dict_enums")),
    )
    op.create_table(
        "dict_import_runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_file", sa.String(length=255), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "imported_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("counts", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column(
            "warnings", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dict_import_runs")),
    )
    op.create_table(
        "dict_incident_groups",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dict_incident_groups")),
    )
    op.create_table(
        "dict_okrugs",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("short", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("prefecture_code", sa.String(length=64), nullable=True),
        sa.Column("outside_moscow", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_dict_okrugs")),
    )
    op.create_table(
        "dict_service_columns",
        sa.Column("col", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("service_code", sa.String(length=64), nullable=False),
        sa.Column("header", sa.String(length=255), nullable=False),
        sa.Column("recipient", sa.String(length=255), nullable=True),
        sa.Column("flag", sa.String(length=64), nullable=True),
        sa.Column("base", sa.String(length=16), nullable=True),
        sa.Column("audience", sa.String(length=16), nullable=False),
        sa.PrimaryKeyConstraint("col", name=op.f("pk_dict_service_columns")),
    )
    op.create_index(
        op.f("ix_dict_service_columns_service_code"), "dict_service_columns", ["service_code"], unique=False
    )
    op.create_table(
        "dict_services",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("short_name", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("okrug_code", sa.String(length=8), nullable=True),
        sa.Column("district_code", sa.String(length=64), nullable=True),
        sa.Column(
            "main_codes", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.Column("phone_synthetic", sa.Boolean(), nullable=False),
        sa.Column("confirmed", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_dict_services")),
    )
    op.create_index(op.f("ix_dict_services_kind"), "dict_services", ["kind"], unique=False)
    op.create_index(op.f("ix_dict_services_okrug_code"), "dict_services", ["okrug_code"], unique=False)
    op.create_table(
        "groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_groups")),
        sa.UniqueConstraint("name", name=op.f("uq_groups_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("operator_number", sa.String(length=16), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("login", name=op.f("uq_users_login")),
    )
    op.create_index(op.f("ix_users_role"), "users", ["role"], unique=False)
    op.create_table(
        "dict_districts",
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("okrug_code", sa.String(length=8), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("dds_service_code", sa.String(length=64), nullable=False),
        sa.Column(
            "aliases", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["okrug_code"], ["dict_okrugs.code"], name=op.f("fk_dict_districts_okrug_code_dict_okrugs")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_dict_districts")),
    )
    op.create_index(op.f("ix_dict_districts_okrug_code"), "dict_districts", ["okrug_code"], unique=False)
    op.create_table(
        "dict_incident_types",
        sa.Column("code", sa.String(length=8), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("sign1", sa.Text(), nullable=True),
        sa.Column("sign1_key", sa.String(length=255), nullable=True),
        sa.Column("sign2", sa.Text(), nullable=True),
        sa.Column("sign3", sa.Text(), nullable=True),
        sa.Column("operator_hint", sa.Text(), nullable=True),
        sa.Column("final_type", sa.Text(), nullable=True),
        sa.Column("ekp_type", sa.Text(), nullable=True),
        sa.Column("response_scenario", sa.String(length=32), nullable=True),
        sa.Column(
            "main_services", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("visible_to_112", sa.Boolean(), nullable=False),
        sa.Column("search_text", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["dict_incident_groups.id"], name=op.f("fk_dict_incident_types_group_id_dict_incident_groups")
        ),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_dict_incident_types")),
    )
    op.create_index(op.f("ix_dict_incident_types_group_id"), "dict_incident_types", ["group_id"], unique=False)
    op.create_index(op.f("ix_dict_incident_types_sign1_key"), "dict_incident_types", ["sign1_key"], unique=False)
    op.create_table(
        "group_members",
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("member_role", sa.String(length=16), nullable=False),
        sa.Column("dds_service_code", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_group_members_group_id_groups"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_group_members_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("group_id", "user_id", name=op.f("pk_group_members")),
    )
    op.create_table(
        "training_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("card_source", sa.String(length=16), nullable=False),
        sa.Column(
            "settings", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["group_id"], ["groups.id"], name=op.f("fk_training_sessions_group_id_groups")),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], name=op.f("fk_training_sessions_teacher_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_training_sessions")),
    )
    op.create_index(op.f("ix_training_sessions_status"), "training_sessions", ["status"], unique=False)
    op.create_table(
        "dict_routing",
        sa.Column("incident_type_code", sa.String(length=8), nullable=False),
        sa.Column("col", sa.Integer(), nullable=False),
        sa.Column("delivery", sa.String(length=16), nullable=False),
        sa.Column("service_type", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["col"], ["dict_service_columns.col"], name=op.f("fk_dict_routing_col_dict_service_columns")
        ),
        sa.ForeignKeyConstraint(
            ["incident_type_code"],
            ["dict_incident_types.code"],
            name=op.f("fk_dict_routing_incident_type_code_dict_incident_types"),
        ),
        sa.PrimaryKeyConstraint("incident_type_code", "col", name=op.f("pk_dict_routing")),
    )
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("format", sa.String(length=8), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("created_by", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], name=op.f("fk_reports_created_by_users")),
        sa.ForeignKeyConstraint(
            ["session_id"], ["training_sessions.id"], name=op.f("fk_reports_session_id_training_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(op.f("ix_reports_session_id"), "reports", ["session_id"], unique=False)
    op.create_table(
        "scenarios",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("roles", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column("card_type_code", sa.String(length=64), nullable=True),
        sa.Column("incident_type_code", sa.String(length=8), nullable=True),
        sa.Column("legend", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False),
        sa.Column(
            "reference_card", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column(
            "reference_dds", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by", sa.Uuid(), nullable=True),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["approved_by"], ["users.id"], name=op.f("fk_scenarios_approved_by_users")),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_scenarios_author_id_users")),
        sa.ForeignKeyConstraint(
            ["incident_type_code"],
            ["dict_incident_types.code"],
            name=op.f("fk_scenarios_incident_type_code_dict_incident_types"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scenarios")),
    )
    op.create_index(op.f("ix_scenarios_incident_type_code"), "scenarios", ["incident_type_code"], unique=False)
    op.create_index(op.f("ix_scenarios_status"), "scenarios", ["status"], unique=False)
    op.create_table(
        "assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("scenario_id", sa.Uuid(), nullable=True),
        sa.Column("student_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(length=8), nullable=False),
        sa.Column("dds_service_code", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["scenario_id"], ["scenarios.id"], name=op.f("fk_assignments_scenario_id_scenarios")),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["training_sessions.id"],
            name=op.f("fk_assignments_session_id_training_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["student_id"], ["users.id"], name=op.f("fk_assignments_student_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignments")),
    )
    op.create_index(op.f("ix_assignments_session_id"), "assignments", ["session_id"], unique=False)
    op.create_index(op.f("ix_assignments_student_id"), "assignments", ["student_id"], unique=False)
    op.create_table(
        "incident_cards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("number", sa.BigInteger(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("assignment_id", sa.Uuid(), nullable=True),
        sa.Column("scenario_id", sa.Uuid(), nullable=True),
        sa.Column("author_id", sa.Uuid(), nullable=True),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column(
            "card_type_codes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "incident_type_codes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("okrug_code", sa.String(length=8), nullable=True),
        sa.Column("district_code", sa.String(length=64), nullable=True),
        sa.Column("address_text", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("has_victims", sa.Boolean(), nullable=False),
        sa.Column("victims_count", sa.Integer(), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("saved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("processing_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["assignments.id"], name=op.f("fk_incident_cards_assignment_id_assignments")
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], name=op.f("fk_incident_cards_author_id_users")),
        sa.ForeignKeyConstraint(
            ["scenario_id"], ["scenarios.id"], name=op.f("fk_incident_cards_scenario_id_scenarios")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["training_sessions.id"], name=op.f("fk_incident_cards_session_id_training_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_incident_cards")),
        sa.UniqueConstraint("number", name=op.f("uq_incident_cards_number")),
    )
    op.create_index(op.f("ix_incident_cards_assignment_id"), "incident_cards", ["assignment_id"], unique=False)
    op.create_index(op.f("ix_incident_cards_session_id"), "incident_cards", ["session_id"], unique=False)
    op.create_index(op.f("ix_incident_cards_status"), "incident_cards", ["status"], unique=False)
    op.create_table(
        "action_events",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("client_event_id", sa.Uuid(), nullable=True),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("assignment_id", sa.Uuid(), nullable=True),
        sa.Column("card_id", sa.Uuid(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column(
            "payload", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("client_ts", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "server_ts", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_action_events_actor_id_users")),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["assignments.id"], name=op.f("fk_action_events_assignment_id_assignments")
        ),
        sa.ForeignKeyConstraint(
            ["card_id"], ["incident_cards.id"], name=op.f("fk_action_events_card_id_incident_cards")
        ),
        sa.ForeignKeyConstraint(
            ["session_id"], ["training_sessions.id"], name=op.f("fk_action_events_session_id_training_sessions")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_events")),
        sa.UniqueConstraint("client_event_id", name=op.f("uq_action_events_client_event_id")),
    )
    op.create_index(op.f("ix_action_events_assignment_id"), "action_events", ["assignment_id"], unique=False)
    op.create_index(op.f("ix_action_events_card_id"), "action_events", ["card_id"], unique=False)
    op.create_index(op.f("ix_action_events_server_ts"), "action_events", ["server_ts"], unique=False)
    op.create_index(op.f("ix_action_events_session_id"), "action_events", ["session_id"], unique=False)
    op.create_table(
        "assessments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=True),
        sa.Column("card_id", sa.Uuid(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column(
            "details", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("grader", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["assignments.id"], name=op.f("fk_assessments_assignment_id_assignments")
        ),
        sa.ForeignKeyConstraint(["card_id"], ["incident_cards.id"], name=op.f("fk_assessments_card_id_incident_cards")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assessments")),
    )
    op.create_index(op.f("ix_assessments_assignment_id"), "assessments", ["assignment_id"], unique=False)
    op.create_index(op.f("ix_assessments_card_id"), "assessments", ["card_id"], unique=False)
    op.create_table(
        "card_service_statuses",
        sa.Column("id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("service_code", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("order_no", sa.String(length=32), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False),
        sa.ForeignKeyConstraint(["actor_id"], ["users.id"], name=op.f("fk_card_service_statuses_actor_id_users")),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["incident_cards.id"],
            name=op.f("fk_card_service_statuses_card_id_incident_cards"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_service_statuses")),
    )
    op.create_index(op.f("ix_card_service_statuses_card_id"), "card_service_statuses", ["card_id"], unique=False)
    op.create_table(
        "card_services",
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("service_code", sa.String(length=64), nullable=False),
        sa.Column("is_main", sa.Boolean(), nullable=False),
        sa.Column("added_by", sa.String(length=16), nullable=False),
        sa.Column("service_type", sa.Text(), nullable=True),
        sa.Column("current_status", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["card_id"], ["incident_cards.id"], name=op.f("fk_card_services_card_id_incident_cards"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["service_code"], ["dict_services.code"], name=op.f("fk_card_services_service_code_dict_services")
        ),
        sa.PrimaryKeyConstraint("card_id", "service_code", name=op.f("pk_card_services")),
    )
    op.create_table(
        "dds_queue_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("card_id", sa.Uuid(), nullable=False),
        sa.Column("dds_service_code", sa.String(length=64), nullable=False),
        sa.Column("assignment_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column(
            "enqueued_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.Column("taken_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignment_id"], ["assignments.id"], name=op.f("fk_dds_queue_items_assignment_id_assignments")
        ),
        sa.ForeignKeyConstraint(
            ["card_id"],
            ["incident_cards.id"],
            name=op.f("fk_dds_queue_items_card_id_incident_cards"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["dds_service_code"], ["dict_services.code"], name=op.f("fk_dds_queue_items_dds_service_code_dict_services")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_dds_queue_items")),
    )
    op.create_index(op.f("ix_dds_queue_items_assignment_id"), "dds_queue_items", ["assignment_id"], unique=False)
    op.create_index(op.f("ix_dds_queue_items_card_id"), "dds_queue_items", ["card_id"], unique=False)
    op.create_table(
        "expert_overrides",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("assessment_id", sa.Uuid(), nullable=False),
        sa.Column("teacher_id", sa.Uuid(), nullable=False),
        sa.Column(
            "changes", sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"), nullable=False
        ),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(timezone=True), server_default=sa.text("(CURRENT_TIMESTAMP)"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["assessments.id"],
            name=op.f("fk_expert_overrides_assessment_id_assessments"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.id"], name=op.f("fk_expert_overrides_teacher_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expert_overrides")),
    )
    op.create_index(op.f("ix_expert_overrides_assessment_id"), "expert_overrides", ["assessment_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expert_overrides_assessment_id"), table_name="expert_overrides")
    op.drop_table("expert_overrides")
    op.drop_index(op.f("ix_dds_queue_items_card_id"), table_name="dds_queue_items")
    op.drop_index(op.f("ix_dds_queue_items_assignment_id"), table_name="dds_queue_items")
    op.drop_table("dds_queue_items")
    op.drop_table("card_services")
    op.drop_index(op.f("ix_card_service_statuses_card_id"), table_name="card_service_statuses")
    op.drop_table("card_service_statuses")
    op.drop_index(op.f("ix_assessments_card_id"), table_name="assessments")
    op.drop_index(op.f("ix_assessments_assignment_id"), table_name="assessments")
    op.drop_table("assessments")
    op.drop_index(op.f("ix_action_events_session_id"), table_name="action_events")
    op.drop_index(op.f("ix_action_events_server_ts"), table_name="action_events")
    op.drop_index(op.f("ix_action_events_card_id"), table_name="action_events")
    op.drop_index(op.f("ix_action_events_assignment_id"), table_name="action_events")
    op.drop_table("action_events")
    op.drop_index(op.f("ix_incident_cards_status"), table_name="incident_cards")
    op.drop_index(op.f("ix_incident_cards_session_id"), table_name="incident_cards")
    op.drop_index(op.f("ix_incident_cards_assignment_id"), table_name="incident_cards")
    op.drop_table("incident_cards")
    op.drop_index(op.f("ix_assignments_student_id"), table_name="assignments")
    op.drop_index(op.f("ix_assignments_session_id"), table_name="assignments")
    op.drop_table("assignments")
    op.drop_index(op.f("ix_scenarios_status"), table_name="scenarios")
    op.drop_index(op.f("ix_scenarios_incident_type_code"), table_name="scenarios")
    op.drop_table("scenarios")
    op.drop_index(op.f("ix_reports_session_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_table("dict_routing")
    op.drop_index(op.f("ix_training_sessions_status"), table_name="training_sessions")
    op.drop_table("training_sessions")
    op.drop_table("group_members")
    op.drop_index(op.f("ix_dict_incident_types_sign1_key"), table_name="dict_incident_types")
    op.drop_index(op.f("ix_dict_incident_types_group_id"), table_name="dict_incident_types")
    op.drop_table("dict_incident_types")
    op.drop_index(op.f("ix_dict_districts_okrug_code"), table_name="dict_districts")
    op.drop_table("dict_districts")
    op.drop_index(op.f("ix_users_role"), table_name="users")
    op.drop_table("users")
    op.drop_table("groups")
    op.drop_index(op.f("ix_dict_services_okrug_code"), table_name="dict_services")
    op.drop_index(op.f("ix_dict_services_kind"), table_name="dict_services")
    op.drop_table("dict_services")
    op.drop_index(op.f("ix_dict_service_columns_service_code"), table_name="dict_service_columns")
    op.drop_table("dict_service_columns")
    op.drop_table("dict_okrugs")
    op.drop_table("dict_incident_groups")
    op.drop_table("dict_import_runs")
    op.drop_table("dict_enums")
    op.drop_table("dict_card_types")
    op.drop_index(op.f("ix_audit_log_event"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_card_number"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_actor_id"), table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
